name : Share Files between Jobs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a output file
        run: |
          mkdir -p build
          echo "Hello from build job" > build/message.txt
          echo "Created file"
          ls -R .

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v6
        with:
          name: build-output
          path: .
      - name: List the Files
        run: |
          echo "Downloaded Files are:"
          pwd
          ls -ltr .
      - name: Read file contents
        run: |
          echo " Contents of file are:
          cat /home/runner/work/gh-demo-1/gh-demo-1/message.txt
    
