name : Share Files between Jobs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create output file
        run: |
          mkdir -p build
          echo "Hello from build job" > build/message.txt
          echo "Created file"
          ls -R .

      - name: upload build artifact
        uses: actions/upload-artifact@4
        with:
          name: build-output
          path: build/
